package silk

const (
	SKP_SILK_NO_ERROR                        = 0
	SKP_SILK_ENC_INPUT_INVALID_NO_OF_SAMPLES = -1
	SKP_SILK_ENC_FS_NOT_SUPPORTED            = -2
	SKP_SILK_ENC_PACKET_SIZE_NOT_SUPPORTED   = -3
	SKP_SILK_ENC_PAYLOAD_BUF_TOO_SHORT       = -4
	SKP_SILK_ENC_INVALID_LOSS_RATE           = -5
	SKP_SILK_ENC_INVALID_COMPLEXITY_SETTING  = -6
	SKP_SILK_ENC_INVALID_INBAND_FEC_SETTING  = -7
	SKP_SILK_ENC_INVALID_DTX_SETTING         = -8
	SKP_SILK_ENC_INTERNAL_ERROR              = -9
	SKP_SILK_DEC_INVALID_SAMPLING_FREQUENCY  = -10
	SKP_SILK_DEC_PAYLOAD_TOO_LARGE           = -11
	SKP_SILK_DEC_PAYLOAD_ERROR               = -12
)
