package silk

const PITCH_EST_MAX_FS_KHZ = 24
const PITCH_EST_FRAME_LENGTH_MS = 40
const PITCH_EST_MAX_FRAME_LENGTH = 960
const PITCH_EST_MAX_FRAME_LENGTH_ST_1 = 240
const PITCH_EST_MAX_FRAME_LENGTH_ST_2 = 480
const PITCH_EST_MAX_LAG = 432
const PITCH_EST_MIN_LAG = 48
const PITCH_EST_NB_SUBFR = 4
const PITCH_EST_D_SRCH_LENGTH = 24
const PITCH_EST_MAX_DECIMATE_STATE_LENGTH = 7
const PITCH_EST_NB_STAGE3_LAGS = 5
const PITCH_EST_NB_CBKS_STAGE2 = 3
const PITCH_EST_NB_CBKS_STAGE2_EXT = 11
const PITCH_EST_CB_mn2 = 1
const PITCH_EST_CB_mx2 = 2
const PITCH_EST_NB_CBKS_STAGE3_MAX = 34
const PITCH_EST_NB_CBKS_STAGE3_MID = 24
const PITCH_EST_NB_CBKS_STAGE3_MIN = 16
